### ISSUE TITLE
Document difference between Data.ListTrie.Map and Data.ListTrie.Patricia.Map

### ISSUE THREAD

**Issue by bitc** [Deewiant/list-tries#4]
It is not clear which one to use in which situations.

Here is maybe a relevant quote from stackoverflow:

> Oh, and since the package didn't state this explicitly anywhere I could see: The "Patricia trie" version is a trie that compresses sequences of single-branch nodes into a single node that stores the common key prefix. So for keys "aabb" and "aabc" you'd get a node with "aab" and then branches "b" and "c". The standard trie always branches one element at a time.

-- [Generic Trie Haskell implementation](http://stackoverflow.com/questions/16084788/generic-trie-haskell-implementation/16086069#16086069)

**Comment by Deewiant** [comment]
Fair point. I think I was mistaken and/or a bit too flexible with the Patricia term (from the [1968 paper](http://dx.doi.org/10.1145/321479.321481)), Wikipedia suggests that while it does refer to the sequence compression, it's only used when the trie structure is based on individual bits instead of arbitrary elements. And the word doesn't seem to have gained traction anyway. Using something more immediately understandable like "compact" would've been better, but perhaps it's not worth it to rename the modules at this point.

But hey, the Cabal description *does* say "use [the Patricia tries] unless you have reasons not to". It's true that it doesn't provide example reasons — perhaps that's because there aren't any. ;-)

**Comment by bitc** [comment]
Somehow I skipped over reading the Cabal description. After reading it, it does indeed clarify things! I suppose this issue can be closed.
