### ISSUE TITLE
GHC 8.6 support

### ISSUE THREAD

**Issue by 23Skidoo** [Deewiant/list-tries#7]
Can you please relax the `base` upper bound on Hackage to `< 4.13` to allow building with GHC 8.6?

**Comment by 23Skidoo** [comment]
Apparently there's also a compile error when building against the latest `containers`.

**Comment by Deewiant** [comment]
Yes, I'm afraid it's not as simple as bumping upper bounds. `containers` 0.6 removes the old semi-strict `insertWith'`-style APIs from `Data.Map` which have been deprecated for a long time. In principle we could remove the one character and use plain `insertWith`, but I'm unsure as to what kind of behavioural effect that has so I'm a bit uncomfortable with doing it just off the cuff.

My understanding is that these APIs were removed in favour of `Data.Map.Strict` because they were misleading and not as strict as people expected, but that they did still behave differently than the fully lazy versions. Perhaps the correct thing to do for `list-tries` would be to use `Data.Map.Strict` internally, but that's another thing that would need a bit deeper evaluation.

Unfortunately my time is really limited these days and `list-tries` has suffered for it. Since I'm unlikely to be able to take the time to do a proper analysis any time soon, I'm going to have to go with the "PRs welcome" response here. Note that fixing the compile error is easy — the key issue is that I'd like to have some understanding of the implications.
